import Head from 'next/head'
import { Informacion } from "../componentes/Informacion"
import { Container } from '@/componentes/Container'
import { Botonmenu } from '@/componentes/Botonmenu'
import { Layout } from '@/componentes/Layout'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Informacion />
        </Container>
      </Layout>
    </>
  )
}
